### ISSUE TITLE
how to get the data

### ISSUE THREAD

**Issue by qianqianyumo** [faebstn96/helix2fan#1]
I want to download the data from the TCIA library, but I don't have permission to download. What do I need to do to get the data？

**Comment by faebstn96** [comment]
Hi @qianqianyumo,
Please see the "Data Access" section in their [TCIA repo](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=52758026#527580266e935eeff87841ec8279dc0eab170832). You just need to sign and submit a [TCIA Restricted License Agreement](https://wiki.cancerimagingarchive.net/download/attachments/4556915/TCIA%20Restricted%20License%2020220519.pdf?version=1&modificationDate=1652964581655&api=v2) to [help@cancerimagingarchive.net](mailto:help@cancerimagingarchive.net). From my experience they respond within a few days.

Best regards
Fabian
