### ISSUE TITLE
flying focal spot

### ISSUE THREAD

**Issue by amberhappy** [faebstn96/helix2fan#10]
Hi！I wonder if this work support flying focal spot now?

**Comment by faebstn96** [comment]
Hi @amberhappy,
Sorry for my delayed reply. Unfortunately, the used backprojection operator does not support shifted source positions that deviate from the circular trajectory. Therefore, the flying focal spot is not considered in the reconstruction. However, the implemented reader (read_data.py) reads out all source shifts (dangles, dz, drho). Feel free to consider them when using a custom backprojection. You can find the shift definitions in the DICOM-CT-PD User Manual (https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=52758026).

**Comment by amberhappy** [comment]
Thanks, that helps me a lot!
I choose odd frames for rebinning and reconstruction(because of FFS). The rebinned result seems like normal, but got all -1000 value in reconstruction volume. 
<img width="827" alt="image" src="https://github.com/faebstn96/helix2fan/assets/20748171/9e87f2ea-44e4-4351-849b-a57afa4b6872">

**Comment by faebstn96** [comment]
Hm, not sure what happened there! Can you maybe share some code?
