### ISSUE TITLE
Asking about nu and du

### ISSUE THREAD

**Issue by musetee** [faebstn96/helix2fan#11]
Hi! Thanks for your great work!
I am kind of confused about the nu and du. I didn't get the LDCT dataset (still waiting for the access) so I apply the code on my own CT raw data get from our medical center, which was in shape of 1376, 144, 2016, in which 1376 is detector number in x direction and 144 is the detector number in z direction, 2016 is the projection number.
1st question:
nu, namely the Rows, should be 144 and nv should be 1376?
2nd question:
as the du from the machine is in radial (d_phi), I have converted it into mm by mutiplying with the dsd, which is 1113 mm in this machine. 
And the dv is DetectorElementAxialSpacing, namely the detector space in Z direction
Have I correctly understood?
3nd question:
If these things are right, why 
x_det = (i_x_det - args.nu / 2) * args.du + 0.5 * args.du 
in rebin_curved_to_flat_detector/_rebin_curved_to_flat_detector_core?
I really hope you can answer these questions, thank you!

**Comment by faebstn96** [comment]
Hi, Please try debugging first with the LDCT dataset. I believe, most of your questions can be quickly answered using the public data.
