### ISSUE TITLE
A circle in fan beam reconstruction result

### ISSUE THREAD

**Issue by debugwangz** [faebstn96/helix2fan#3]
![图片](https://user-images.githubusercontent.com/12813597/222433883-39982951-7f35-4001-abd1-9e8fe637c53a.png)
Should there be a circle in the reconstruction result?

**Comment by faebstn96** [comment]
Hi @debugwangz,
The regions out of that visible circle suffer from [truncation](https://doi.org/10.53347/rID-70537) which means that they can not be properly recognized as information from some projection views is missing there. Reason is the data acquisition itself and not the reconstruction algorithm. Vendor reconstructions sometimes mask these regions as the information there is not complete.
