### ISSUE TITLE
Two bright spots in reconstruction result of C002 

### ISSUE THREAD

**Issue by debugwangz** [faebstn96/helix2fan#4]
![图片](https://user-images.githubusercontent.com/12813597/225299815-98d1efff-f13c-4431-ba35-0d7de3a2f6e2.png)

There are two bright spots in the sinogram and reconstruction result of C002. 
The first index and last index of helical projections are 0 and 1200.
Is it also because of the data?

Thank you for your assistance.

**Comment by faebstn96** [comment]
I also recognized that some scans in that data base contain artifacts. Please compare your custom reconstructions with the proprietary reconstructions also provided in the data set. But I assume this is part of the data!
