### ISSUE TITLE
ValueError: negative dimensions are not allowed when running main.py

### ISSUE THREAD

**Issue by harshitAgr** [faebstn96/helix2fan#5]
Hi, I get below error when trying to generate fan_beam projections from LDCT data.
I will try to investigate the problem further. I wonder if it you already know how to resolve it quickly?
 `python main.py --path_dicom /mnt/new/datasets/lowDoseCT/manifest-1648648375084/LDCT-and-Projection-data/N001/01-31-2022-NA-NA-63397/1.000000-Full\ Dose\ Projections-25858 --idx_proj_start 0 --idx_proj_stop 100`

`proj_rebinned = np.zeros((args.rotview, args.nu, args.nz_rebinned), dtype=np.float32)
ValueError: negative dimensions are not allowed`

Thanks,

**Comment by faebstn96** [comment]
Hi @harshitAgr,
A colleague of mine had a similar problem very recently. It seems that some of the head scans (including N001 that you are using) are acquired with a negative pitch/table direction and the code is not handling that correctly so far. I will look into this. For now you can use the following head scans N005, N024, N030, N047, N051. At least for them I know that the rebinning is working.

Please note that for some head projection data some geometric parameters are completely missing. For those cases, the error will tell that it cannot read out a specific parameter. So, you need to be picky with those scans unfortunately.

Sorry about that, I will look into the problem. I mainly tested the code on the abdomen data. There everything seems to work fine.

Best,
Fabian

**Comment by harshitAgr** [comment]
Hi, thanks, I tried N005 which worked without problem.
