### ISSUE TITLE
About variables nu, nv, du, dv

### ISSUE THREAD

**Issue by Deming77** [faebstn96/helix2fan#7]
Thank you for sharing this repository! 

I have two questions about the above-mentioned variables:

1. In Noo et al. "Single-slice rebinning method for helical cone-beam CT" (1999), the v direction is parallel to z. Should this be the rows instead of columns? 
2. According to Dataset DICOM_User_manual,  dv is the DetectorElementAxialSpacing of row elements, but in the parser, it says "Scanner detector pixel spacing in column direction". 

Thanks,

**Comment by Deming77** [comment]
Nvm about the first question. I think you referred dataset.Rows to nu, which should be the detector columns.

**Comment by musetee** [comment]
> Nvm about the first question. I think you referred dataset.Rows to nu, which should be the detector columns.

I am confused about these thins, and opened another issue, could you please take a look at this? #11
