### ISSUE TITLE
how to accelerate rebin operation

### ISSUE THREAD

**Issue by listar0810** [faebstn96/helix2fan#8]
Hello, thx for your greate job!
I adopt the 2016Mayo challenge data, it has 40 thousands+ view of every patient.
I have tried to rebin it for four hours, is there any methods to accelerate the operation?
Many thx again

**Comment by listar0810** [comment]
And I still wanna to know if this function 'rebin_curved_to_flat_detector' refer to any literatures？Many thx @faebstn96

**Comment by faebstn96** [comment]
Hi @listar0810,Indeed, rebinning can take a while when processing plenty/very large scans. I did not look too much into function acceleration yet. You might be able to quickly parallelize the rebinning loops using PyTorch libraries like Numba though. Please have a look there, I do not have the capacity to do that right now.The function rebin_curved_to_flat_detector does not follow a particular publication but is based on the geometry considering the curved detector provided by the rebinning (Noo et al.) on the one hand and the flat detector geometry required by the FBP reconstruction algorithm on the other hand.Hope that helped!On 13. Jul 2023, at 09:03, listar0810 ***@***.***> wrote:﻿
And I still wanna to know if this function 'rebin_curved_to_flat_detector' refer to any literatures？Many thx @faebstn96

**Comment by listar0810** [comment]
Thx a lot!

**Comment by listar0810** [comment]
@faebstn96 Hi, I would like to know if helix2fan supports the case of flying focal spot, many thx!
