### ISSUE TITLE
Helical to fan-beam geometry for multiple rotations

### ISSUE THREAD

**Issue by g-stanic** [faebstn96/helix2fan#9]
Hi, do you have any experience with rebinning scans that contain multiple rotations? As far as I understood, rebinning works only for 2pi, which is also something I experienced in action. Could you give a hint on the parameters that could potentially control the behavior of the algorithm in this case?

**Comment by faebstn96** [comment]
Hi @g-stanic,
The current code actually rebins projection data from multiple helical rotations to one single 2pi set of projections. In fact, multiple detector rotations are even required to cover the full length of a patient as diagnostic CT scanners usually use  rather narrow detectors with a limited number of rows. You can just download the referred public projection data and have a look.
I hope that helped. Let me know if you have any questions!

**Comment by g-stanic** [comment]
Hi, I must have made a mistake while setting up the code then. I am trying to adapt your repo to be able to rebin projections other than DICOM-CTPD so something was off when having a couple of turns. Thanks for the quick reponse.
